---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.0
  - 2.7.0
  - 3.0.0
  - 3.1.0
  - 3.2.0
before_install:
  - gem update --system # Update RubyGems to avoid potential issues
  - gem install bundler # Use the latest version of Bundler available