name: Ruby

on: [push,pull_request]

jobs:
  rspec:
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0, 3.1, 3.2, 3.3]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake spec
